
Info:
  class: InfoModule
  module: modules
  function: run


Keylogger:
  class: InfoModule
  module: modules
  function: run

Screenshot:
  class: ScreenshotModule
  module: modules
  function: run





