
Info:
  class: InfoModule
  module: modules
  function: run


Mail:
  class: MailModule
  module: modules
  function: run

Disk:
  class: DiskModule
  module: modules
  function: run

Key:
  class: KeyModule
  module: modules
  function: run




